# Generated by Django 3.2.10 on 2021-12-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('ph_no', models.IntegerField(max_length=14, unique=True)),
                ('msg', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
