# Generated by Django 3.2.10 on 2021-12-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactMe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='ph_no',
            field=models.SmallIntegerField(max_length=14, unique=True),
        ),
    ]
