# Generated by Django 3.2.10 on 2021-12-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactMe', '0002_alter_contactme_ph_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='ph_no',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
